### ISSUE TITLE
Compatibility with Azure Devops

### ISSUE THREAD

**Issue by filipverlee** [Redisrupt/mermaid-diagrams#10]
First of all great tool! But is there anyway you could add Azure Devops also. Would be great in combination with the AzureDevops Wiki. Thnx in advance!

**Comment by royriojas** [comment]
Not sure I follow. What's the url of Azure Devops? 
In any case PRs welcome! more than happy to merge adding a new url where this might be eanbled!

**Comment by howard0su** [comment]
Check the PR #11

**Comment by royriojas** [comment]
Thank you @howard0su, really appreciated

**Comment by royriojas** [comment]
I just merged this, so I will close this ticket

**Comment by mrpmorris** [comment]
@filipverlee Now that MS have moved to dev.azure.com do you think you might submit a new PR for that site too?
