### ISSUE TITLE
Lines do not appear

### ISSUE THREAD

**Issue by alechp** [Redisrupt/mermaid-diagrams#2]
### Summary
* 👍 Shapes & arrowheads appear
* 👎 Lines do not appear

### Visual
🥇 Viewed using [VSCode's Markdown Enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) 
<img width="540" alt="screen shot 2018-03-10 at 11 18 55 am" src="https://user-images.githubusercontent.com/3058939/37245957-36e110b0-2455-11e8-89c8-ff66104f0633.png">

🥈 Viewed using Chrome extension:
<img width="540" alt="screen shot 2018-03-10 at 11 18 14 am" src="https://user-images.githubusercontent.com/3058939/37245959-3b9f4f7c-2455-11e8-89bc-7bd5c8050c0e.png">

**Comment by royriojas** [comment]
@alechp interesting, can you try to view the [chart here](https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKQVtDaHJpc3RtYXNdIC0tPnxHZXQgbW9uZXl8IEIoR28gc2hvcHBpbmcpCkIgLS0-IEN7TGV0IG1lIHRoaW5rfQpDIC0tPnxPbmV8IERbTGFwdG9wXQpDIC0tPnxUd298IEVbaVBob25lXQpDIC0tPnxUaHJlZXwgRltDYXJdCg)

It might be that we need to upgrade the mermaidjs version

**Comment by alechp** [comment]
@royriojas 

<img width="1792" alt="screen shot 2018-03-11 at 11 50 48 am" src="https://user-images.githubusercontent.com/3058939/37257170-aa176e6c-2522-11e8-8f90-ede3b5844025.png">

**Comment by harlantwood** [comment]
I had similar issues, which I fixed in #6.

**Comment by royriojas** [comment]
closed by #6
