### ISSUE TITLE
Un-minified source code not included

### ISSUE THREAD

**Issue by maackle** [Redisrupt/mermaid-diagrams#5]
This extension is effectively closed-source. I'm not going to install it until I can read the source code.

**Comment by harlantwood** [comment]
The (mermaid) source is here: https://github.com/knsv/mermaid -- you can build it yourself with `yarn release`.

**Comment by royriojas** [comment]
Hi @maackle, as @harlantwood mentioned. The source can be obtained in the mermaid repo. You can always clone the repo and build it yourself and even install this extension from source as well, to avoid any issues with the minimized version. 

Closing for now.
