### ISSUE TITLE
can these be run in a website

### ISSUE THREAD

**Issue by amitmawkin** [Redisrupt/mermaid-diagrams#8]
If we want to run this in a website is it possible?

**Comment by royriojas** [comment]
Closed by mistake @amitmawkin. 

This extension is powered by [mermaid.js](https://mermaidjs.github.io/) and it is probably what you want to use if you control the website where you plan to embed the diagrams.

If you don't control it, you can always clone this repo and change the urls in the manifest file to match the url of the site where you want to use this.

Hope this helps

**Comment by amitmawkin** [comment]
thanks... let me try
